# Generated by Django 4.2 on 2024-07-22 19:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("message", "0001_initial"),
        ("clients", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Mailing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(verbose_name="Дата первой отправки"),
                ),
                (
                    "ended_at",
                    models.DateTimeField(verbose_name="Дата окончания отправки"),
                ),
                (
                    "periodicity",
                    models.CharField(
                        choices=[
                            ("Раз в день", "Раз в день"),
                            ("Раз в неделю", "Раз в неделю"),
                            ("Раз в месяц", "Раз в месяц"),
                        ],
                        max_length=30,
                        verbose_name="Периодичность",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Завершена", "Завершена"),
                            ("Создана", "Создана"),
                            ("Запущена", "Запущена"),
                        ],
                        default="Запущена",
                        max_length=30,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активна"),
                ),
                (
                    "client",
                    models.ManyToManyField(
                        related_name="mailing_list",
                        to="clients.client",
                        verbose_name="Клиенты",
                    ),
                ),
                (
                    "message",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="message.message",
                        verbose_name="Сообщение",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "рассылка",
                "verbose_name_plural": "рассылки",
            },
        ),
        migrations.CreateModel(
            name="Attempt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "attempt_time",
                    models.DateTimeField(
                        auto_now=True, null=True, verbose_name="Дата последней попытки"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("successful", "Успешно"),
                            ("unsuccessful", "Не успешно"),
                        ],
                        max_length=30,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "server_response",
                    models.CharField(max_length=100, verbose_name="Ответ сервера"),
                ),
                (
                    "client",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="clients.client",
                        verbose_name="клиент",
                    ),
                ),
                (
                    "mailing",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mailing.mailing",
                        verbose_name="Попытка",
                    ),
                ),
            ],
            options={
                "verbose_name": "попытка",
                "verbose_name_plural": "попытки",
            },
        ),
    ]
