version: '3.8'
services:
  pgdb:
    image: postgres:latest
    container_name: pgdb
    env_file:
      - .env.dev
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - pgdbdata:/var/lib/postgresql/data

  redis:
    image: redis:latest
    container_name: redis_server
    expose:
      - 6379

  app:
    build: .
    container_name: app
    command: python manage.py runserver 0.0.0.0:8000
    env_file:
      - .env.dev
    volumes:
      - .:/usr/src/app
    ports:
      - '8000:8000'
    depends_on:
      - pgdb
      - redis

volumes:
  pgdbdata: null